// Generated by CoffeeScript 1.9.3
(function() {
  TEIditto.addBehaviors({
    "line": "div"
  });

  TEIditto.getHTML5('xml/ox-ms_abinger_c56-0011.xml', null, function(h5) {
    var app, left_margin_zones, main_zone;
    $("#TEI").html(h5);
    main_zone = $("tei-zone[type=main]");
    $("tei-line:has(tei-add[place=superlinear])").css("margin-top", ".5em");
    $("tei-line:has(tei-add[place=sublinear])").each(function(i, line) {
      var $line, add, adds, j, len, results;
      $line = $(line);
      $line.css("margin-bottom", ".5em");
      adds = $line.find("tei-add[place=sublinear]");
      results = [];
      for (i = j = 0, len = adds.length; j < len; i = ++j) {
        add = adds[i];
        if (adds[i - 1] != null) {
          results.push($(add).css("padding-left", $(adds[i - 1]).text().length + "em"));
        } else {
          results.push(void 0);
        }
      }
      return results;
    });
    $("tei-line:has(tei-add[place=superlinear])").each(function(i, line) {
      var $line, add, adds, j, len, results;
      $line = $(line);
      $line.css("margin-top", ".5em");
      adds = $line.find("tei-add[place=superlinear]");
      results = [];
      for (i = j = 0, len = adds.length; j < len; i = ++j) {
        add = adds[i];
        if (adds[i - 1] != null) {
          results.push($(add).css("padding-left", $(adds[i - 1]).text().length + "em"));
        } else {
          results.push(void 0);
        }
      }
      return results;
    });
    left_margin_zones = $("tei-zone[type=left_margin]");
    left_margin_zones.css("margin-top", main_zone.position().top);
    left_margin_zones.each(function(i, lmz) {
      return $(lmz).css("top", (i * (100 / left_margin_zones.length)) + "%");
    });
    app = new annotator.App();
    app.include(annotator.ui.main);
    return app.start();
  });

}).call(this);
